from random import randint
"""imports the 'randint' function from the 'random' module. 
This enables random numbers to be generated by te computer

"""
count = 1 #initializes the value of the variable 'count' to 1
print("WELCOME TO MY ADDITION TEST PROGRAM")
print("____________________________________")
while count <= 3:
    num1 = randint(10,99) #Generates a number between 10 and 99
    num2 = randint(10,99) #Generates a number between 10 and 99
    answer = int(input(f'What is {num1} + {num2}? ')) #Requests for user's answer
    if answer == num1 + num2: # Compares answer to arithmetic operation performed
        print (f'Great! You got it! The answer is {num1 + num2} You got {count} correct in a row')
        count+=1 #increases 'count' by 1 after every iteration
        if count==4:
            print("Congratulations!!! . You have done very well")
    else:
            print (f'Wrong! The answer is {num1 + num2}')
            num1 = randint(10,99)
            num2 = randint(10,99)
            count = 1